application: app-deployer
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

- name: pycrypto
  version: "2.6"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /_ah/spi/.*
  script: api.application

- url: /.*
  script: app_deployer.app
